dist: focal
language: c
compiler:
#  - clang
  - gcc
python:
  - "3.6"
before_install:
  - sudo apt-get install -y g++ ninja-build flac python3-setuptools python3-pip
  - sudo pip3 install meson gcovr cpp-coveralls
script:
  - mkdir build_release
  - cd build_release
  - meson -Dbuildtype=release -Db_coverage=True ..
  - ../test/test_flac_integration_runner.py --no-run --song-dir ../test/data/extra/ --exe ./test_flac_integration
  - ninja && ninja test && ninja coverage
  - coveralls -r .. -b . --exclude subprojects --exclude examples --exclude test

