---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          sudo apt-get install -y \
              g++ ninja-build flac python3-setuptools python3-pip
          sudo pip install meson gcovr cpp-coveralls
      - name: Build
        run: |
          mkdir build
          cd build
          meson setup -Dbuildtype=release -Db_coverage=True ..
          ninja
      - name: Test
        run: |
          cd build
          ../test/test_flac_integration_runner.py \
              --no-run \
              --data-dir ../test/data/extra/ \
              --exe ./test_flac_integration
          ninja test
      - name: Demo test
        run: |
          cd build
          echo "1058e2a061aecd46ddfbc6330230d1f412e36bbd02c7ffdefbb992926e3c00ef  -" > ref.txt
          ./flac_decoder ../test/data/short.flac | sha256sum -c ref.txt
      - name: Coverage
        run: |
          cd build
          ninja coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
